CRUD Airline
mazyaa/BE_KM7_AirJourney_Final-Project pull request #30
Opened 2024-12-02 12:42 UTC by adibnajwan

2024-12-03 09:22 UTC, adibnajwan commented
semangat

2024-12-03 13:35 UTC, norplys requested changes

2024-12-03 13:35 UTC, norplys commented on src/routes/airline.js
> +    airlineMiddleware.checkAirlineNameExist,
double middleware

2024-12-03 13:35 UTC, norplys commented on src/routes/airline.js
> +    airlineMiddleware.checkAirlineById,
validate id params, take it from common middlewares

2024-12-03 13:35 UTC, norplys commented on src/routes/airline.js
> +    airlineMiddleware.checkAirlineById,
Add check by code and name

2024-12-03 13:35 UTC, norplys commented on src/controllers/airline.js
> +    data: airlineData
remove data

2024-12-04 03:29 UTC, norplys commented on src/routes/airlines.js
> +    airlineMiddleware.checkAirlineById,
validate id paramsnya

2024-12-04 03:48 UTC, norplys requested changes

2024-12-04 03:48 UTC, norplys commented on src/middlewares/airline.js
> +  const currentAirline = res.locals.airport;
its airline not airport

2024-12-04 03:48 UTC, norplys commented on src/services/airline.js
> +export async function createAirline(payload) {
await nya masukkin ke variabel data trus return datanya ( all of it )

2024-12-05 10:31 UTC, norplys approved these changes
LGTM !

2024-12-05 10:31 UTC, norplys commented on src/services/airline.js
> +}
buat ke return data semua

2024-12-05 10:31 UTC, norplys commented on src/repositories/airline.js
> +      updatedAt: new Date()
updateAt jan di update manual

2024-12-05 10:31 UTC, norplys commented on src/routes/index.js
> +  airline(router);
s wkwkw

2024-12-05 10:31 UTC, merged